<script setup>
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import ApplicationService from '../../services/ApplicationService'
import AuditService from '../../services/AuditService'
const route = useRoute(); const router = useRouter(); const application = ref(null); const loading = ref(true); const error = ref('')
async function load () { loading.value = true; error.value = ''; try { application.value = await ApplicationService.get(route.params.id); if (!application.value) error.value = 'La postulación no existe o no está disponible.'; else AuditService.record({ accion: 'consulta_postulacion', modulo: 'postulaciones', entidad: 'postulacion', entidadId: application.value.id, descripcion: `Consulta de postulación de ${application.value.name}` }).catch(() => {}) } catch (e) { error.value = e.message || 'No fue posible cargar la postulación.' } finally { loading.value = false } }
onMounted(load)
</script>
<template><div><button type="button" class="mb-5 text-sm font-semibold text-brand-600" @click="router.push('/admin/postulaciones')">← Volver a postulaciones</button><div v-if="loading" class="py-16 text-center text-sm text-stone-400">Cargando detalle...</div><p v-else-if="error" class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ error }}</p><template v-else><header class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-brand-600">Postulación</p><h2 class="mt-1 font-display text-2xl font-bold text-stone-900">{{ application.name }}</h2><p class="mt-1 text-sm text-stone-500">{{ application.vacancyCode }} · {{ application.vacancyTitle }}</p></div><button v-if="application.candidateId" type="button" class="btn-secondary px-4 py-2 text-sm" @click="router.push(`/admin/candidatos/${application.candidateId}`)">Ver candidato</button></header><div class="grid gap-5 lg:grid-cols-2"><section class="card border border-stone-100 p-6 shadow-sm"><h3 class="font-display font-bold">Información de contacto</h3><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-stone-400">Correo</dt><dd class="font-medium">{{ application.email }}</dd></div><div><dt class="text-stone-400">Teléfono</dt><dd class="font-medium">{{ application.phone }}</dd></div><div><dt class="text-stone-400">Ubicación</dt><dd class="font-medium">{{ application.location }}</dd></div><div><dt class="text-stone-400">Fecha</dt><dd class="font-medium">{{ new Date(application.createdAt).toLocaleString('es-ES') }}</dd></div></dl></section><section class="card border border-stone-100 p-6 shadow-sm"><h3 class="font-display font-bold">Perfil profesional</h3><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-stone-400">Profesión u oficio</dt><dd class="font-medium">{{ application.profession }}</dd></div><div><dt class="text-stone-400">Nivel académico</dt><dd class="font-medium">{{ application.academicLevel || 'No especificado' }}</dd></div><div><dt class="text-stone-400">Experiencia</dt><dd class="font-medium">{{ application.yearsExperience ?? 'No especificada' }}</dd></div><div><dt class="text-stone-400">Estado</dt><dd class="font-medium capitalize">{{ application.administrativeStatus }}</dd></div></dl></section><section class="card border border-stone-100 p-6 shadow-sm lg:col-span-2"><h3 class="font-display font-bold">Mensaje de presentación</h3><p class="mt-3 whitespace-pre-line text-sm leading-6 text-stone-600">{{ application.message || 'No dejó un mensaje de presentación.' }}</p></section></div></template></div></template>
