<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import ApplicationService from '../../services/ApplicationService'

const router = useRouter(); const applications = ref([]); const loading = ref(false); const error = ref(''); const search = ref(''); const status = ref('')
const visible = computed(() => applications.value.filter(app => (!status.value || app.administrativeStatus === status.value) && `${app.name} ${app.email} ${app.vacancyTitle} ${app.vacancyCode}`.toLowerCase().includes(search.value.trim().toLowerCase())))
const statusClass = value => ({ nueva: 'bg-brand-50 text-brand-700', revisada: 'bg-sage-50 text-sage-700', archivada: 'bg-stone-100 text-stone-600', descartada: 'bg-red-50 text-red-700' }[value] || 'bg-stone-100 text-stone-600')
async function load () { loading.value = true; error.value = ''; try { applications.value = await ApplicationService.getAll() } catch (e) { error.value = e.message || 'No fue posible cargar las postulaciones.' } finally { loading.value = false } }
onMounted(load)
</script>
<template><div><header class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-brand-600">Proceso de selección</p><h2 class="mt-1 font-display text-2xl font-bold text-stone-900">Postulaciones</h2><p class="mt-1 text-sm text-stone-500">Consulta y da seguimiento a todas las postulaciones recibidas.</p></div><button type="button" class="btn-secondary px-4 py-2 text-sm" @click="load">Actualizar</button></header><p v-if="error" class="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ error }}</p><section class="card overflow-hidden border border-stone-100 shadow-sm"><div class="flex flex-col gap-3 border-b border-stone-100 p-4 sm:flex-row"><input v-model="search" class="input-field flex-1" placeholder="Buscar por candidato, correo o vacante" /><select v-model="status" class="input-field sm:w-52"><option value="">Todos los estados</option><option value="nueva">Nueva</option><option value="revisada">Revisada</option><option value="archivada">Archivada</option><option value="descartada">Descartada</option></select></div><div v-if="loading" class="py-16 text-center text-sm text-stone-400">Cargando postulaciones...</div><div v-else-if="!visible.length" class="py-16 text-center text-sm text-stone-400">No se encontraron postulaciones.</div><div v-else class="divide-y divide-stone-100"><article v-for="app in visible" :key="app.id" class="flex flex-col gap-3 p-5 lg:flex-row lg:items-center lg:justify-between"><div><p class="font-display font-semibold text-stone-900">{{ app.name }}</p><p class="mt-1 text-sm text-stone-500">{{ app.vacancyCode }} · {{ app.vacancyTitle || 'Vacante no disponible' }}</p><p class="mt-1 text-xs text-stone-400">{{ app.email }} · {{ new Date(app.createdAt).toLocaleDateString('es-ES') }}</p></div><div class="flex items-center gap-3"><span class="rounded-full px-2.5 py-1 text-xs font-semibold capitalize" :class="statusClass(app.administrativeStatus)">{{ app.administrativeStatus }}</span><button type="button" class="btn-secondary px-3 py-2 text-xs" @click="router.push(`/admin/postulaciones/${app.id}`)">Ver detalle</button></div></article></div></section></div></template>
