<script setup>
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import CandidateService from '../../services/CandidateService'
const route = useRoute(); const router = useRouter(); const candidate = ref(null); const history = ref([]); const loading = ref(true); const error = ref('')
async function load () { loading.value = true; error.value = ''; try { candidate.value = await CandidateService.get(route.params.id); if (!candidate.value) error.value = 'El candidato no existe o no está disponible.'; else history.value = await CandidateService.getHistory(candidate.value.id) } catch (e) { error.value = e.message || 'No fue posible cargar el candidato.' } finally { loading.value = false } }
onMounted(load)
</script>
<template><div><button type="button" class="mb-5 text-sm font-semibold text-brand-600" @click="router.push('/admin/candidatos')">← Volver a candidatos</button><div v-if="loading" class="py-16 text-center text-sm text-stone-400">Cargando candidato...</div><p v-else-if="error" class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ error }}</p><template v-else><header class="mb-6"><p class="text-sm font-semibold text-brand-600">Banco de candidatos</p><h2 class="mt-1 font-display text-2xl font-bold text-stone-900">{{ candidate.name }}</h2><p class="mt-1 text-sm text-stone-500">{{ candidate.email }} · {{ candidate.status }}</p></header><div class="grid gap-5 lg:grid-cols-2"><section class="card border border-stone-100 p-6 shadow-sm"><h3 class="font-display font-bold">Perfil</h3><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-stone-400">Profesión u oficio</dt><dd class="font-medium">{{ candidate.profession }}</dd></div><div><dt class="text-stone-400">Nivel académico</dt><dd class="font-medium">{{ candidate.academicLevel || 'No especificado' }}</dd></div><div><dt class="text-stone-400">Ubicación</dt><dd class="font-medium">{{ candidate.location }}</dd></div><div><dt class="text-stone-400">Experiencia</dt><dd class="font-medium">{{ candidate.yearsExperience ?? 'No especificada' }}</dd></div></dl></section><section class="card border border-stone-100 p-6 shadow-sm"><h3 class="font-display font-bold">Contacto</h3><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-stone-400">Correo</dt><dd class="font-medium">{{ candidate.email }}</dd></div><div><dt class="text-stone-400">Teléfono</dt><dd class="font-medium">{{ candidate.phone }}</dd></div><div><dt class="text-stone-400">LinkedIn</dt><dd class="font-medium">{{ candidate.linkedinUrl || 'No registrado' }}</dd></div><div><dt class="text-stone-400">Etiquetas</dt><dd class="mt-1 flex flex-wrap gap-1"><span v-for="tag in candidate.tags" :key="tag" class="rounded-full bg-brand-50 px-2 py-1 text-xs text-brand-700">{{ tag }}</span><span v-if="!candidate.tags.length" class="text-stone-500">Sin etiquetas</span></dd></div></dl></section><section class="card border border-stone-100 p-6 shadow-sm lg:col-span-2"><h3 class="font-display font-bold">Historial de postulaciones</h3><div v-if="!history.length" class="mt-4 text-sm text-stone-400">No hay postulaciones registradas.</div><div v-else class="mt-4 divide-y divide-stone-100"><button v-for="item in history" :key="item.id" type="button" class="flex w-full items-center justify-between py-3 text-left hover:text-brand-700" @click="router.push(`/admin/postulaciones/${item.id}`)"><span><strong class="font-semibold">{{ item.vacancyCode }}</strong> · {{ item.vacancyTitle }}</span><span class="text-xs capitalize text-stone-500">{{ item.administrativeStatus }}</span></button></div></section></div></template></div></template>
